<a href="https://colab.research.google.com/github/Amjad-Bin-Aslam/Data-Analysis-Practice/blob/main/04_numPy/01_numPy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy (Numerical Python)
NumPy is an open-source Python library used for numerical computing, particularly for working with arrays, matrices, and high-level mathematical functions.

It provides:
* A powerful N-dimensional array object (ndarray)
* Broadcasting capabilities for arithmetic operations
* Mathematical, logical, and statistical functions on arrays
* Tools for linear algebra, Fourier transforms, and random number generation
* Integration with C/C++/Fortran code for performance



## Key points
* NumPy arrays are homogeneous (all elements have the same data type)
* Much faster and more efficient than Python lists for large-scale numerical data
* Forms the foundation for scientific computing in Python

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# Create Array
* All elements in a NumPy array have the same data type (e.g., all integers, all floats).
* Can be 1D, 2D, 3D, or higher dimensions.
* Supports vectorized operations — you can perform arithmetic on the whole array at once.
* It is the core data structure for numerical computing in Python.

In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
my_list = [1,2,3,4,5,6]
print(np.array(my_list))
print(type(my_list))

[1 2 3 4 5 6]
<class 'list'>


In [ ]:
my_list = ["Ahmad", "Amjad","Talha"]
arr_from_list = np.array(my_list)
print(arr_from_list)
print(type(my_list))
print(type(arr_from_list))

['Ahmad' 'Amjad' 'Talha']
<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
# 2D array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


# Changing Datatype


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)
print(arr)
arr = arr.astype('float32')
print(arr.dtype)
print(arr)

int64
[1 2 3 4 5]
float32
[1. 2. 3. 4. 5.]


# Array Functions




## arange()
Create array with a range of numbers

In [ ]:
arr = np.arange(1,11)
print(arr)
arr1 = np.arange(1,11,2)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


## zeros() and ones()
Create an array filled with zeros and ones

In [ ]:
# zeros
arr1 = np.zeros((2,3)) # 2 rows , 3 columns
print(arr1)
#  ones
arr0 = np.ones((2,2))
print(arr0)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


## linespace()
Create an array of evenly spaced numbers


In [ ]:
arr = np.linspace(0,1,5) # 5 numbers from 0 to 1
print(arr)

[0.   0.25 0.5  0.75 1.  ]


## reshape()
change the shape of an array

In [ ]:
arr = np.arange(6)
print(arr)
# reshape
arr2 = arr.reshape((2,3))
print(arr2)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


## append()
Add the element to an array(return the new array)

In [ ]:
arr = np.array([1,2,3,4])
print(arr)
# add the element
arr1 = np.arange(8)
print(arr1)
apend_arr = np.append(arr,arr1)
print("Appended array: ",apend_arr)

[1 2 3 4]
[0 1 2 3 4 5 6 7]
Appended array:  [1 2 3 4 0 1 2 3 4 5 6 7]


## insert()
Insert element add specific index

In [ ]:
arr = np.arange(6)
print(arr)
new_arr = np.insert(arr,1,10) # insert 10 at index 10
print("element added: ",new_arr)

[0 1 2 3 4 5]
element added:  [ 0 10  1  2  3  4  5]


## random()
generates the random number between the 0 and 1

In [ ]:
arr = np.random.random(6)
print(arr)

[0.56976454 0.01218372 0.25117178 0.99597996 0.9464834  0.73083436]


In [ ]:
from numpy import random
x = random.randint(5,size=(3,5))
print(x)

[[0 0 2 4 3]
 [2 0 2 0 4]
 [4 3 2 2 1]]


In [ ]:
x = random.choice([3,5,6,7])
print(x)

3


## delete()
Delete element at specific index

In [ ]:
arr = np.arange(7)
print(arr)
new_arr = np.delete(arr,2) # remove element at index 2
print(new_arr)

[0 1 2 3 4 5 6]
[0 1 3 4 5 6]


## sort()
Use to sort the element in order

In [ ]:
arr = np.array([23,4,57,24,0,1,56])

print(np.sort(arr))

[ 0  1  4 23 24 56 57]


## Mathematical Functions

In [ ]:
a = np.array([1,4,8])

print(np.sqrt(a)) # Square Root
print(np.square(a)) # Square
print(np.sum(a)) # Sum
print(np.max(a)) # Maximum
print(np.min(a)) # Minimum
print(np.mean(a)) # Average
print(np.average(a)) # Average




[1.         2.         2.82842712]
[ 1 16 64]
13
8
1
4.333333333333333
4.333333333333333


# Array Attributes


## .shape
return the dimension(number of rows and columns)

In [ ]:
arr = np.arange(6,dtype=int)
print(arr.shape)
arr1 = np.arange(6).reshape(2,3)
print(arr1)
print(arr1.shape)

(6,)
[[0 1 2]
 [3 4 5]]
(2, 3)


## .ndim
Return the number of dimensioin

In [ ]:
print("number of dimensions in arr1: ",arr1.ndim)

number of dimensions in arr1:  2


## .size
Return the count of number of elements in array

In [ ]:
arr = np.arange(6).reshape(2,3)
print(arr)
print(arr.size)

[[0 1 2]
 [3 4 5]]
6


## .dtype
Tell the data type of elements in array

In [ ]:
arr = np.array([1,2,3,4], dtype=float)
print(arr.dtype)


float64


## .itemsize
Memory size(in bytes) of one element

In [ ]:
arr = np.array([4,5,6,7])
print("size in bytes for each element: ",arr.itemsize)
print("data type of element: ", arr.dtype)

size in bytes for each element:  8
data type of element:  int64


## .nbytes
Total number of bytes used by array in the memory

In [ ]:
arr = np.array([1,2,3,4], dtype=np.int64)
print(arr.nbytes)

32


# Array Operations

## Arithmetic Operations

In [ ]:
import numpy as np
a = np.array([10,20,30])
b = np.array([1,2,3])

print(a + b) # addition
print( a - b) # subtraction
print( a * b) # Multiplication
print( a / b) # Division
print(a % b) # Modulus

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
[0 0 0]


## Scalar Operations
Numbers with array

In [ ]:
a = np.array([12,10,3])

print(arr + 2)
print( arr * 2)

[3 4 5 6]
[2 4 6 8]


## Comparison Operations


In [ ]:
arr = np.array([5, 10, 15, 20])

print(arr > 10)
print(arr == 15)

[False False  True  True]
[False False  True False]


# Indexing and Slicing

In [ ]:
arr = np.arange(6)
print(arr[1])
print(arr)

1
[0 1 2 3 4 5]
